name: 从源码编译 gcc

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'GCC 版本'
        type: string
        required: true
        default: 13.2.0
      system:
        description: '指定目标平台:'
        type: choice
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
      target:
        description: 'GCC 目标机器，例如: aarch64-linux-gnu'
        type: string
        required: true
        default: aarch64-linux-gnu
      glibc_version:
        description: 'GCC 目标依赖的 glibc 版本，将传递给 --with-glibc-version'
        type: string
        required: true
        default: '2.38'

run-name: 从源码编译 ${{ inputs.target }}-gcc-${{ inputs.version }}-glibc-${{ inputs.glibc_version }}

jobs:
  build_gcc:
    name: 编译 GCC
    runs-on: ${{ inputs.system }}
    steps:
      - uses: actions/checkout@v4

      - name: 下载 gcc ${{ inputs.version }} 源码，并解压
        run: |
          wget https://ftp.gnu.org/gnu/gcc/gcc-${{ inputs.version }}/gcc-${{ inputs.version }}.tar.gz
          tar --extract --gzip --file=gcc-${{ inputs.version }}.tar.gz

      - name: 下载依赖源码
        run: |
          cd gcc-${{ inputs.version }}
          ./contrib/download_prerequisites

      - name: 配置 gcc
        run: |
          cd gcc-${{ inputs.version }}
          ./configure  \
              --prefix=/usr/local/${{ inputs.target }}-gcc-${{ inputs.version }}-glibc-${{ inputs.glibc_version }} \
              --target=${{ inputs.target }} \
              --with-glibc-version=${{ inputs.glibc_version }} \
              --enable-languages=c,c++ \
              --disable-multilib \
              CFLAGS="-O3 -Wno-error"  \
              CXXFLAGS="-O3 -Wno-error"

      - name: 编译安装 gcc
        run: |
          cd gcc-${{ inputs.version }}
          make -j16
          sudo make install

      - name: 打包 gcc
        run: |
          cd /usr/local
          sudo tar --create --gzip \
              --file=${{ inputs.target }}-gcc-${{ inputs.version }}-glibc-${{ inputs.glibc_version }}.tar.gz \
              ${{ inputs.target }}-gcc-${{ inputs.version }}-glibc-${{ inputs.glibc_version }}
